"""Unit tests for the document quality gate (spec C2.5).

Covers:
- Metric computation (valid_char_ratio / text_density) on synthetic text.
- Fixture PDFs (low_quality / scan_like / healthy) generated by
  ``generate_quality_fixtures.py``.
- Extension dispatch (only registered formats inspected).
- enabled=False passthrough.
- Threshold boundary behavior (>= passes).
- Config parsing from LoaderSettings (via Settings.from_dict).
"""

from pathlib import Path

import pytest

from src.libs.loader.quality_gate import (
    DEFAULT_QUALITY_EXTENSIONS,
    QUALITY_REJECT_MESSAGE,
    DocumentQualityGate,
    QualityCheckResult,
    QualityGateConfig,
)

FIXTURES = Path(__file__).parent.parent / "fixtures"

# Minimal but complete settings dict (all _require_* fields satisfied).
def _minimal_settings_dict(loader_block: dict) -> dict:
    return {
        "llm": {"provider": "openai", "model": "m", "temperature": 0.0, "max_tokens": 1},
        "embedding": {"provider": "openai", "model": "e", "dimensions": 3},
        "vector_store": {"provider": "chroma", "persist_directory": "./x", "collection_name": "c"},
        "retrieval": {"dense_top_k": 5, "sparse_top_k": 5, "fusion_top_k": 3, "rrf_k": 60},
        "rerank": {"enabled": False, "provider": "none", "model": "none", "top_k": 3},
        "evaluation": {"enabled": False, "provider": "custom", "metrics": ["hit_rate"]},
        "observability": {
            "log_level": "INFO", "trace_enabled": False,
            "trace_file": "./logs/t.jsonl", "structured_logging": False,
        },
        "loader": loader_block,
    }


# ---------------------------------------------------------------------------
# Fixtures helpers
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def gate() -> DocumentQualityGate:
    return DocumentQualityGate(QualityGateConfig())


@pytest.fixture(scope="module")
def low_quality_pdf() -> Path:
    path = FIXTURES / "low_quality.pdf"
    if not path.exists():
        pytest.skip("low_quality.pdf fixture not generated; run generate_quality_fixtures.py")
    return path


@pytest.fixture(scope="module")
def scan_like_pdf() -> Path:
    path = FIXTURES / "scan_like.pdf"
    if not path.exists():
        pytest.skip("scan_like.pdf fixture not generated; run generate_quality_fixtures.py")
    return path


@pytest.fixture(scope="module")
def healthy_pdf() -> Path:
    path = FIXTURES / "healthy.pdf"
    if not path.exists():
        pytest.skip("healthy.pdf fixture not generated; run generate_quality_fixtures.py")
    return path


# ---------------------------------------------------------------------------
# Metric computation (pure logic, no PDF)
# ---------------------------------------------------------------------------

class TestValidCharRatio:
    def test_pure_ascii_text(self, gate):
        ratio = gate._compute_valid_char_ratio("Hello World 123")
        assert ratio == 1.0

    def test_chinese_text(self, gate):
        ratio = gate._compute_valid_char_ratio("检索增强生成")
        assert ratio == 1.0

    def test_mixed_with_garbage(self, gate):
        # 5 valid + 5 invalid non-whitespace chars -> 0.5
        text = "Hello" + "«»§¶†"
        ratio = gate._compute_valid_char_ratio(text)
        assert ratio == pytest.approx(0.5)

    def test_whitespace_ignored(self, gate):
        ratio = gate._compute_valid_char_ratio("H e l l o\t\n 1 2 3 ")
        assert ratio == 1.0

    def test_empty_text_returns_one(self, gate):
        # Empty -> 1.0 so text_density is the deciding metric instead.
        assert gate._compute_valid_char_ratio("") == 1.0


class TestTextDensity:
    def test_all_pages_text_bearing(self, gate):
        pages = ["Hello World 123 " * 10] * 3
        assert gate._compute_text_density(pages) == 1.0

    def test_no_pages_text_bearing(self, gate):
        pages = ["", " ", "«»§¶"]  # below min_chars_per_page
        assert gate._compute_text_density(pages) == 0.0

    def test_partial_density(self, gate):
        good = "Hello World 123 " * 10  # >= 50 valid chars
        bad = "hi"  # < min_chars_per_page (50)
        density = gate._compute_text_density([good, bad, bad, good])
        assert density == pytest.approx(0.5)

    def test_empty_page_list(self, gate):
        assert gate._compute_text_density([]) == 0.0


# ---------------------------------------------------------------------------
# Extension dispatch & master switch
# ---------------------------------------------------------------------------

class TestDispatch:
    def test_pdf_registered_by_default(self):
        assert ".pdf" in DEFAULT_QUALITY_EXTENSIONS

    def test_non_registered_format_passes(self, tmp_path):
        md = tmp_path / "doc.md"
        md.write_text("# anything")
        gate = DocumentQualityGate(QualityGateConfig(extensions=[".pdf"]))
        result = gate.check(md)
        assert result.passed is True
        assert result.sampled_pages == 0

    def test_disabled_gate_passes_anything(self, tmp_path):
        pdf = tmp_path / "bad.pdf"
        pdf.write_bytes(b"not really a pdf")
        gate = DocumentQualityGate(QualityGateConfig(enabled=False))
        result = gate.check(pdf)
        assert result.passed is True

    def test_applies_to_case_insensitive(self):
        cfg = QualityGateConfig()
        assert cfg.applies_to("A/B/report.PDF") is True
        assert cfg.applies_to("A/B/report.txt") is False

    def test_missing_file_rejected(self, tmp_path):
        gate = DocumentQualityGate()
        result = gate.check(tmp_path / "ghost.pdf")
        assert result.passed is False
        assert result.reason is not None and QUALITY_REJECT_MESSAGE in result.reason

    def test_corrupt_pdf_rejected(self, tmp_path):
        pdf = tmp_path / "corrupt.pdf"
        pdf.write_bytes(b"%PDF-1.4 broken content")
        gate = DocumentQualityGate()
        result = gate.check(pdf)
        assert result.passed is False
        assert result.reason is not None and QUALITY_REJECT_MESSAGE in result.reason


# ---------------------------------------------------------------------------
# Threshold boundary
# ---------------------------------------------------------------------------

class TestThresholds:
    def test_ratio_exactly_at_threshold_passes(self):
        # 80 valid + 20 invalid = exactly 0.80 -> >= passes
        text = "A" * 80 + "«" * 20
        cfg = QualityGateConfig(min_valid_char_ratio=0.80)
        gate = DocumentQualityGate(cfg)
        assert gate._compute_valid_char_ratio(text) == pytest.approx(0.80)
        # Direct threshold comparison mirrors gate.check logic
        assert gate._compute_valid_char_ratio(text) >= cfg.min_valid_char_ratio

    def test_density_exactly_at_threshold_passes(self):
        good = "Hello World 123 " * 10
        cfg = QualityGateConfig(min_text_density=0.50)
        gate = DocumentQualityGate(cfg)
        # 2/4 pages text-bearing = 0.50 -> >= passes
        assert gate._compute_text_density([good, "", good, ""]) >= cfg.min_text_density

    def test_custom_strict_thresholds_reject_healthy(self, healthy_pdf):
        cfg = QualityGateConfig(min_valid_char_ratio=1.01)  # impossible
        gate = DocumentQualityGate(cfg)
        result = gate.check(healthy_pdf)
        assert result.passed is False


# ---------------------------------------------------------------------------
# Fixture PDF end-to-end checks
# ---------------------------------------------------------------------------

class TestFixturePDFs:
    def test_healthy_pdf_passes(self, gate, healthy_pdf):
        result = gate.check(healthy_pdf)
        assert result.passed is True
        assert result.reason is None
        assert result.valid_char_ratio >= 0.80
        assert result.text_density >= 0.50
        assert result.sampled_pages == 3

    def test_low_quality_pdf_rejected_by_ratio(self, gate, low_quality_pdf):
        result = gate.check(low_quality_pdf)
        assert result.passed is False
        assert result.valid_char_ratio < 0.80
        assert QUALITY_REJECT_MESSAGE in result.reason
        assert "有效字符占比" in result.reason

    def test_scan_like_pdf_rejected_by_density(self, gate, scan_like_pdf):
        result = gate.check(scan_like_pdf)
        assert result.passed is False
        assert result.text_density < 0.50
        assert QUALITY_REJECT_MESSAGE in result.reason
        assert "可识别文本密度" in result.reason

    def test_sampled_pages_respects_preview_limit(self, low_quality_pdf):
        gate = DocumentQualityGate(QualityGateConfig(preview_pages=2))
        result = gate.check(low_quality_pdf)
        assert result.sampled_pages == 2

    def test_single_page_pdf_not_killed_by_page_count(self, tmp_path):
        """1-page PDF with normal text must pass despite few pages."""
        from tests.fixtures.generate_quality_fixtures import build_healthy
        pdf = tmp_path / "single.pdf"
        build_healthy(pdf, pages=1)
        gate = DocumentQualityGate()
        result = gate.check(pdf)
        assert result.passed is True


# ---------------------------------------------------------------------------
# Result serialization
# ---------------------------------------------------------------------------

class TestQualityCheckResult:
    def test_to_dict_shape(self):
        r = QualityCheckResult(
            passed=False, valid_char_ratio=0.4321, text_density=0.25,
            sampled_pages=3, reason="x",
        )
        d = r.to_dict()
        assert d["passed"] is False
        assert d["valid_char_ratio"] == 0.4321
        assert d["text_density"] == 0.25
        assert d["sampled_pages"] == 3
        assert d["reason"] == "x"


# ---------------------------------------------------------------------------
# Settings integration
# ---------------------------------------------------------------------------

class TestSettingsIntegration:
    def test_loader_settings_parses_quality_gate(self):
        from src.core.settings import Settings
        data = _minimal_settings_dict(
            {"extract_markdown_images": True,
             "quality_gate": {"enabled": True, "min_valid_char_ratio": 0.9}}
        )
        settings = Settings.from_dict(data)
        assert settings.loader.quality_gate == {"enabled": True, "min_valid_char_ratio": 0.9}

    def test_loader_settings_without_quality_gate(self):
        from src.core.settings import Settings
        data = _minimal_settings_dict({"extract_markdown_images": True})
        settings = Settings.from_dict(data)
        assert settings.loader.quality_gate is None

    def test_actual_settings_yaml_loads(self):
        """The real config/settings.yaml must parse with the new key present."""
        from src.core.settings import load_settings
        yaml_path = Path(__file__).parent.parent.parent / "config" / "settings.yaml"
        settings = load_settings(str(yaml_path))
        qg = settings.loader.quality_gate
        assert qg is not None
        assert qg["enabled"] is True
        assert qg["min_valid_char_ratio"] == pytest.approx(0.80)
        assert qg["preview_pages"] == 3


# ---------------------------------------------------------------------------
# Pipeline integration (mocked storage deps via monkeypatched run internals)
# ---------------------------------------------------------------------------

class TestPipelineIntegration:
    def _make_pipeline(self, tmp_path, monkeypatch, gate_result=None):
        """Build a minimal IngestionPipeline-like object for run() testing.

        We construct a real IngestionPipeline but patch every heavy component
        so run() can be exercised end-to-end without LLM/Chroma/Embedding.
        """
        from src.core.settings import Settings
        from src.ingestion.pipeline import IngestionPipeline

        data = _minimal_settings_dict({"quality_gate": {"enabled": True}})
        data["ingestion"] = {
            "chunk_size": 100, "chunk_overlap": 0, "splitter": "recursive", "batch_size": 10,
        }
        data["vector_store"]["persist_directory"] = str(tmp_path / "chroma")
        settings = Settings.from_dict(data)

        # Patch all heavy component constructors before instantiation.
        from src.ingestion import pipeline as pl
        from src.libs.loader import loader_factory as lf
        from src.libs.embedding import embedding_factory as ef
        from src.libs.vector_store import vector_store_factory as vf
        from src.ingestion.chunking import document_chunker as dc
        from src.ingestion.transform import chunk_refiner as cr
        from src.ingestion.transform import metadata_enricher as me
        from src.ingestion.transform import image_captioner as ic
        from src.ingestion.embedding import dense_encoder as de
        from src.ingestion.storage import bm25_indexer as bi
        from src.ingestion.storage import vector_upserter as vu
        from src.ingestion.storage import image_storage as ims

        monkeypatch.setattr(pl, "SQLiteIntegrityChecker", lambda **kw: _FakeIntegrity())
        monkeypatch.setattr(pl, "DocumentChunker", lambda s: _FakeChunker())
        monkeypatch.setattr(pl, "ChunkRefiner", lambda s: _FakeRefiner())
        monkeypatch.setattr(pl, "MetadataEnricher", lambda s: _FakeEnricher())
        monkeypatch.setattr(pl, "ImageCaptioner", lambda s: _FakeCaptioner())
        monkeypatch.setattr(pl, "VectorUpserter", lambda s, collection_name=None: _FakeUpserter())
        monkeypatch.setattr(pl, "BM25Indexer", lambda index_dir=None: _FakeBM25())
        monkeypatch.setattr(pl, "ImageStorage", lambda **kw: _FakeImageStore())
        monkeypatch.setattr(ef.EmbeddingFactory, "create", lambda s: _FakeEmbedding())
        # BatchProcessor is constructed with keyword args in the pipeline.
        monkeypatch.setattr(pl, "BatchProcessor", lambda **kw: _FakeBatchProcessor())
        # Settings.embedding.provider is accessed for logging only.
        if gate_result is not None:
            fake_gate = _FakeGate(gate_result)
            monkeypatch.setattr(pl, "DocumentQualityGate", lambda cfg=None: fake_gate)
        else:
            monkeypatch.setattr(pl, "DocumentQualityGate", lambda cfg=None: DocumentQualityGate(cfg))

        return IngestionPipeline(settings, collection="test_qg", force=True)

    def test_low_quality_pdf_rejected_before_load(self, tmp_path, monkeypatch, low_quality_pdf):
        from src.ingestion.pipeline import IngestionPipeline

        pipeline = self._make_pipeline(tmp_path, monkeypatch)
        result = pipeline.run(str(low_quality_pdf))

        assert result.success is False
        assert result.rejected is True
        assert QUALITY_REJECT_MESSAGE in result.error
        assert "quality_check" in result.stages
        # Loader must NOT have been invoked (no load stage recorded)
        assert "loading" not in result.stages
        # Integrity history recorded the rejection
        assert pipeline.integrity_checker.calls == [("mark_failed", "quality_rejected")]
        pipeline.close()

    def test_healthy_pdf_passes_gate_and_reaches_load(self, tmp_path, monkeypatch, healthy_pdf):
        pipeline = self._make_pipeline(tmp_path, monkeypatch)
        result = pipeline.run(str(healthy_pdf))

        assert result.rejected is False
        assert result.stages["quality_check"]["passed"] is True
        # Loading stage recorded -> gate did not block the healthy doc
        assert "loading" in result.stages
        pipeline.close()

    def test_gate_rejection_uses_fake_gate_result(self, tmp_path, monkeypatch, healthy_pdf):
        """Even a healthy doc is rejected when the gate says no (wiring check)."""
        from src.libs.loader.quality_gate import QualityCheckResult

        failing = QualityCheckResult(passed=False, reason="forced rejection")
        pipeline = self._make_pipeline(tmp_path, monkeypatch, gate_result=failing)
        result = pipeline.run(str(healthy_pdf))

        assert result.rejected is True
        assert result.error == "forced rejection"
        pipeline.close()


# ---------------------------------------------------------------------------
# Fakes for pipeline integration tests
# ---------------------------------------------------------------------------

class _FakeIntegrity:
    def __init__(self):
        self.calls = []

    def compute_sha256(self, path):
        return "fakehash" * 8

    def should_skip(self, file_hash):
        return False

    def mark_success(self, file_hash, path, collection):
        self.calls.append(("mark_success", None))

    def mark_failed(self, file_hash, path, error):
        self.calls.append(("mark_failed", error))


class _FakeEmbedding:
    def embed(self, texts):
        return [[0.1, 0.2, 0.3] for _ in texts]


class _FakeChunker:
    def split_document(self, document):
        from src.core.types import Chunk
        return [
            Chunk(
                id=f"{document.id}_0000_abc",
                text=document.text[:200],
                metadata={"chunk_index": 0, "source_path": document.metadata.get("source_path", "")},
                source_ref=document.id,
            )
        ]


class _FakeRefiner:
    use_llm = False

    def transform(self, chunks, trace=None):
        return chunks


class _FakeEnricher:
    use_llm = False

    def transform(self, chunks, trace=None):
        return chunks


class _FakeCaptioner:
    use_llm = False
    llm = None

    def transform(self, chunks, trace=None):
        return chunks


class _FakeBatchProcessor:
    def process(self, chunks, trace=None):
        class R:
            dense_vectors = [[0.1, 0.2, 0.3] for _ in chunks]
            sparse_stats = [{"doc_length": 10, "unique_terms": 5, "term_frequencies": {}} for _ in chunks]
        return R()


class _FakeUpserter:
    def upsert(self, chunks, vectors, trace=None):
        return [c.id for c in chunks]


class _FakeBM25:
    def add_documents(self, stats, collection=None, doc_id=None, trace=None):
        pass


class _FakeImageStore:
    def register_image(self, **kw):
        pass

    def close(self):
        pass


class _FakeGate:
    def __init__(self, result):
        self._result = result

    def check(self, path):
        return self._result
